url: https://y7kim.github.io
baseurl:
plugins: ['jekyll/scholar']

# Site settings
title: Julius Busecke
email: jbusecke@princeton.edu
description: "Julius Busecke is a Postdoctoral Research Associate at Princeton University, studying Oceanography with a focus on oceanic eddy mixing and biogechemistry."
author: Julius Busecke
keywords: “Julius Busecke, J Busecke, Busecke,Ocean, Oceanography, Salinity, Freshwater, Upper Ocean, Mixing “
robots: index
# # Team names, titles and social links
# people:
# - name: Kay Garland
#   pic: 1
#   position: Lead Designer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: stack-overflow
#       url: #
#
# - name: Larry Parker
#   pic: 2
#   position: Lead Marketer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: linkedin
#       url: #
#
# - name: Diana Petersen
#   pic: 3
#   position: Lead Developer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: google-plus
#       url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# stack-overflow bitbucket
social:
  - title: twitter
    url: http://twitter.com/JuliusBusecke
  # - title: linkedin
  #   url: https://www.linkedin.com/in/julius-busecke-a47027117/
  - title: github
    url: http://github.com/jbusecke

# Postal address (add as many lines as necessary)
address:
  - line: 408A Guyot Hall
  - line: Princeton, NJ 08544
  - line: USA

# Build settings
markdown: kramdown
permalink: pretty

# Bibliography settings
scholar:
  style: american-meteorological-society
  locale: en

  sort_by: year, month
  order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bib

  replace_strings: true
  join_strings:    true

  # details_dir:    bibliography
  # details_layout: bibtex.html
  # details_link:   Details

  query: "@*"
