url: https://y7kim.github.io
baseurl:
plugins: ['jekyll/scholar']

# Site settings
title: Julius Busecke
email: julius@ldeo.columbia.edu
description: "Julius Busecke is a Postdoctoral Research Associate at Princeton University, studying Oceanography with a focus on oceanic eddy mixing and biogechemistry."
author: Julius Busecke
keywords: “Julius Busecke, J Busecke, Busecke,Ocean, Oceanography, Salinity, Freshwater, Upper Ocean, Mixing “
robots: index

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# stack-overflow bitbucket
social:
  - title: twitter
    url: http://twitter.com/JuliusBusecke
  # - title: linkedin
  #   url: https://www.linkedin.com/in/julius-busecke-a47027117/
  - title: github
    url: http://github.com/jbusecke

social_academic:
  # - title: figshare
  #   url: https://figshare.com/authors/_/3809782
  - title: google-scholar
    url: https://scholar.google.de/citations?hl=de&user=nXQo4RkAAAAJ

# Postal address (add as many lines as necessary)
address:
  - line: LDEO, 61 Rte 9W, Oceanography 206
  - line: Palisades NY 10964
  - line: USA

# Build settings
markdown: kramdown
permalink: pretty

# Bibliography settings
scholar:
  style: american-meteorological-society
  locale: en

  sort_by: year, month
  order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bib

  replace_strings: true
  join_strings:    true

  # details_dir:    bibliography
  # details_layout: bibtex.html
  # details_link:   Details

  query: "@*"
